import { useState } from "react";
import { CheckCircle2, Mail, MapPin, Phone } from "lucide-react";
import { PageHero, PageShell, SectionLabel, CONTACT_EMAIL, GENERAL_EMAIL, PRIMARY_PHONE, SECONDARY_PHONE, WHATSAPP_HREF } from "../components/SiteChrome";

export default function Contact() {
  const [sent, setSent] = useState(false);
  return <PageShell>
    <PageHero eyebrow="Contact us" title={<>Let’s make the next step feel <span className="font-display italic text-[#f6d77a]">simple.</span></>} intro="Ask a question, find your nearest centre or tell us a little about the young person you are supporting." />
    <section className="container grid gap-12 py-24 lg:grid-cols-[.8fr_1.2fr] lg:py-32"><div><SectionLabel>Reach the team</SectionLabel><h2 className="mt-5 text-5xl font-medium leading-[.96] tracking-[-.05em] sm:text-6xl">A real person will <span className="font-display italic text-[#7a6316]">reply.</span></h2><div className="mt-10 space-y-5 text-sm"><a className="contact-line" href={`mailto:${CONTACT_EMAIL}`}><Mail size={18} /><span><b>Website email</b>{CONTACT_EMAIL}</span></a><a className="contact-line" href={`mailto:${GENERAL_EMAIL}`}><Mail size={18} /><span><b>General Gmail</b>{GENERAL_EMAIL}</span></a><a className="contact-line" href="tel:+918886665295"><Phone size={18} /><span><b>Primary phone / WhatsApp</b>{PRIMARY_PHONE}</span></a><a className="contact-line" href="tel:+918886665294"><Phone size={18} /><span><b>Secondary phone</b>{SECONDARY_PHONE}</span></a><div className="contact-line"><MapPin size={18} /><span><b>Centres</b>Hyderabad · Surat</span></div></div></div><div className="form-card">{sent ? <div className="flex min-h-[360px] flex-col items-center justify-center text-center"><CheckCircle2 className="text-[#0e9c8c]" size={54} /><h2 className="mt-6 text-4xl font-medium">Message received.</h2><p className="mt-4 max-w-[360px] text-sm leading-6 text-muted-copy">This demo form is ready to connect to your email or CRM. For now, please use WhatsApp or email for the fastest reply.</p></div> : <form className="space-y-5" onSubmit={(e) => { e.preventDefault(); setSent(true); }}><p className="section-kicker text-[#7a6316]">Send a message</p><h2 className="text-4xl font-medium">What can we help with?</h2><label><span>Name</span><input className="theme-input mt-2 w-full rounded-xl px-4 py-3" required /></label><label><span>Email or WhatsApp number</span><input className="theme-input mt-2 w-full rounded-xl px-4 py-3" required /></label><label><span>Your message</span><textarea className="theme-input mt-2 min-h-[130px] w-full rounded-xl px-4 py-3" required /></label><button className="btn-dark w-full rounded-full px-5 py-4 text-sm font-bold" type="submit">Send enquiry</button><a className="btn-primary flex w-full items-center justify-center rounded-full px-5 py-4 text-sm font-bold" href={WHATSAPP_HREF} target="_blank" rel="noreferrer">Or message us on WhatsApp</a></form>}</div></section>
  </PageShell>;
}
