import { useState } from "react";
import { ChevronDown, Mail } from "lucide-react";
import { PageHero, PageShell, SectionLabel, CONTACT_EMAIL } from "../components/SiteChrome";

const faqs = [
  ["What happens in a typical TYA session?", "Every session starts with a Mission — a real-feeling challenge that gives young people a reason to use the skill. They work in their Pod, take on roles, make decisions, reflect and try again. It is active, social and structured — not another class where they sit and listen."],
  ["What exactly will Young Adults (YA) learn at TYA?", "TYA goes beyond academics. Young people explore communication, leadership, independent thinking, emotional intelligence, decision-making, creativity, entrepreneurship, teamwork, problem-solving, adaptability and much more. The focus is on skills that help them navigate life, not just exams."],
  ["Is TYA a coaching or tuition program?", "No. TYA is a learning community, not a tuition centre. There are no textbooks, lectures or conventional classrooms. Learning happens through Missions, games, discussions, activities, videos, challenges, experiences and conversations — often without them even realising they're learning."],
  ["As a Young Adult, will I have to speak or perform in front of everyone?", "Not necessarily — and certainly not on day one. TYA is designed to help young people build confidence gradually. They participate in smaller groups, interact with their Pod and take on different roles. Over time, they are encouraged to find their voice and express themselves comfortably."],
  ["What if my child is shy or doesn't participate?", "That's okay. There is no pressure to become an instant extrovert. Our mentors create a supportive environment where every YA can participate at their own pace. We encourage them, understand their comfort levels and gradually help them step beyond them."],
  ["What is a TYA Pod?", "A Pod is the small community within TYA where young people meet, interact and learn together. Pods are created based on factors such as age group and location, allowing members to build familiarity, friendships and a sense of belonging while learning from different personalities and perspectives."],
  ["How does TYA help beyond the sessions?", "The goal is not for learning to end when the session does. Young people are encouraged to take what they discover into everyday lives — at home, school, college, with friends and eventually into their communities. TYA is about turning learning into action."],
  ["How do you know whether a YA is actually growing?", "TYA isn't about marks or grades. Growth can show up in how a young person communicates, participates, takes responsibility, handles challenges, works with others, makes decisions and reflects on their experiences. We aim to make that growth visible through participation, reflection and a record of their journey."],
  ["What role do parents play in TYA?", "Parents are important partners, but TYA is ultimately the young person's space. We encourage parents to support the journey without taking over it. Where appropriate, parents can be kept informed about participation, experiences and areas of growth, while giving the YA room to discover and express themselves."],
  ["How do I know if TYA is right for my young person?", "TYA is organised into three stages: Class 6 to 9, Class 10 to 12 and Grads. Each stage adapts the Missions and language to where the learner is — from building confidence and communication to career, financial and future planning."],
  ["How do parents see progress?", "You receive a written TYA Growth Card every month. It is not a grade or a certificate — it is a clear snapshot of five/six behaviours the coach actually observed. Example: confidence, collaboration, decision making, adaptability and ownership."],
  ["How are safety and consistency handled?", "Batches are intentionally structured for 30 young people, with coach-led Pods and clear roles for participation. Coaches are verified, pick-up is named, and every centre follows the same term structure so parents know what week one is building towards."],
  ["What makes TYA different?", "TYA doesn't try to tell young people who they should become. It creates experiences that help them discover who they are, what they can do and what they can become. They meet. They question. They experiment. They fail safely. They try again. They learn from one another. And slowly, they become Transformed Young Adults."],
] as const;

export default function Experience() {
  const [open, setOpen] = useState<number | null>(0);
  const [question, setQuestion] = useState("");
  return <PageShell>
    <PageHero eyebrow="The TYA experience" title={<>Good questions deserve <span className="font-display italic text-[#f6d77a]">proper</span> answers.</>} intro="The practical details that help young people and parents understand what happens inside a TYA Pod." />
    <section className="container grid gap-12 py-24 lg:grid-cols-[.65fr_1.35fr] lg:py-32"><div className="lg:sticky lg:top-28 lg:self-start"><SectionLabel>FAQs</SectionLabel><h2 className="mt-5 text-5xl font-medium leading-[.96] tracking-[-.05em] sm:text-6xl">What you want to <span className="font-display italic text-[#7a6316]">know.</span></h2><p className="mt-7 text-lg leading-8 text-muted-copy">Still have a question? Write to the team and we’ll help you find the right answer.</p><a className="btn-dark mt-7 inline-flex rounded-full px-5 py-3 text-sm font-bold" href={`mailto:${CONTACT_EMAIL}`}>Ask the TYA team <Mail className="ml-2" size={15} /></a></div><div className="faq-list">{faqs.map(([q, a], index) => <div className="faq-item" key={q}><button className="faq-trigger" onClick={() => setOpen(open === index ? null : index)} aria-expanded={open === index}><span><span className="mr-3 text-xs font-bold text-[#f28d63]">{String(index + 1).padStart(2, "0")}</span>{q}</span><ChevronDown className={open === index ? "rotate-180" : ""} size={18} /></button>{open === index && <p className="faq-answer single">{a}</p>}</div>)}</div></section>
    <section className="soft-panel py-20"><div className="container max-w-3xl"><SectionLabel>Ask your own question</SectionLabel><h2 className="mt-4 text-4xl font-medium">What would make the decision easier?</h2><form className="mt-7 flex flex-col gap-3 sm:flex-row" onSubmit={(e) => { e.preventDefault(); window.location.href = `mailto:${CONTACT_EMAIL}?subject=Question for TYA Club&body=${encodeURIComponent(question)}`; }}><input className="theme-input flex-1 rounded-full px-5 py-3" required value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="Type your question here" /><button className="btn-dark rounded-full px-6 py-3 text-sm font-bold" type="submit">Send question</button></form></div></section>
  </PageShell>;
}
