import { ArrowRight, Building2, Check, Users, Zap } from "lucide-react";
import { Link } from "wouter";
import { PageHero, PageShell, SectionLabel, WHATSAPP_HREF } from "../components/SiteChrome";

export default function Franchise() {
  return <PageShell>
    <PageHero eyebrow="Franchise with TYA" title={<>Bring a room for growth to your <span className="font-display italic headline-accent headline-accent--butter"><strong className="headline-impact">city.</strong></span></>} intro="A first-draft overview of the TYA partnership opportunity. We are building a thoughtful network of people who believe young adults deserve better spaces to grow." />
    <section className="container py-16 lg:py-24"><div className="rounded-[2rem] bg-[#f28d63] p-8 sm:p-12 lg:p-16"><SectionLabel>Partnership overview · draft</SectionLabel><h2 className="mt-5 max-w-[780px] text-balance text-5xl font-medium leading-[.96] tracking-[-.05em] sm:text-6xl">The next TYA room could start with <span className="font-display italic headline-accent headline-accent--coral"><strong className="headline-impact">you.</strong></span></h2><p className="mt-7 max-w-[620px] text-lg leading-8 text-[#3e4245]/75">This page will be refined with your final franchise model, investment details, territory structure and partner criteria.</p><a className="btn-dark mt-8 inline-flex rounded-full px-6 py-4 text-sm font-bold" href={WHATSAPP_HREF} target="_blank" rel="noreferrer">Start a conversation <ArrowRight className="ml-2" size={16} /></a></div></section>
    <section className="soft-panel py-16 lg:py-24"><div className="container"><SectionLabel>Why partner with TYA</SectionLabel><div className="mt-12 grid gap-4 md:grid-cols-3"><article className="content-card"><Building2 className="text-[#0e9c8c]" /><h3>Purpose-led model</h3><p>Bring practical, experience-led learning to young adults in your city.</p></article><article className="content-card"><Zap className="text-[#f28d63]" /><h3>Distinctive experience</h3><p>Missions, Pods and Growth Cards create a clear, differentiated parent proposition.</p></article><article className="content-card"><Users className="text-[#7a6316]" /><h3>Community-minded</h3><p>Build a local centre where young adults, families and coaches feel they belong.</p></article></div></div></section>
    <section className="container grid gap-12 py-16 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><SectionLabel>What the conversation will cover</SectionLabel><h2 className="mt-5 text-5xl font-medium leading-[.96] tracking-[-.05em]">A partnership built for <span className="font-display italic headline-accent headline-accent--butter"><strong className="headline-impact">care.</strong></span></h2></div><ul className="space-y-4 text-lg leading-8 text-muted-copy">{["Your city, centre and local community", "Coach recruitment and programme delivery", "Parent experience, admissions and trial sessions", "Brand, curriculum and operational support", "The commercial model and next steps"].map((item) => <li key={item} className="flex gap-3"><Check className="mt-1 shrink-0 text-[#0e9c8c]" size={20} />{item}</li>)}</ul></section>
    <section className="soft-panel py-20"><div className="container flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><SectionLabel>Interested?</SectionLabel><h2 className="mt-4 text-4xl font-medium">Let’s explore the fit.</h2></div><Link className="btn-dark rounded-full px-6 py-4 text-sm font-bold" href="/contact">Contact the team</Link></div></section>
  </PageShell>;
}
