import { ArrowRight, Building2, Check, TrendingUp, Users, Zap } from "lucide-react";
import { Link } from "wouter";
import { PageHero, PageShell, SectionIntro, WHATSAPP_HREF } from "../components/SiteChrome";

export default function Franchise() {
  return <PageShell>
    <PageHero eyebrow="Franchise with TYA" title={<>Bring the revolution to <span className="font-display italic headline-accent headline-accent--butter"><strong className="headline-impact">your city.</strong></span></>} intro="A first-draft overview of the TYA partnership opportunity. We are building a thoughtful network of people who believe young adults deserve better spaces to grow." />
    <section className="container py-16 lg:py-24"><div className="rounded-[2rem] bg-[#f28d63] p-8 sm:p-12 lg:p-16"><SectionIntro eyebrow="Partnership overview · draft" title={<>The next TYA room could start with <span className="font-display italic headline-accent headline-accent--coral"><strong className="headline-impact">you.</strong></span></>} description="This page will be refined with your final franchise model, investment details, territory structure and partner criteria." action={<a className="btn-dark inline-flex items-center rounded-full px-6 py-4 text-sm font-bold" href={WHATSAPP_HREF} target="_blank" rel="noreferrer">Start a conversation <ArrowRight className="ml-2" size={16} /></a>} className="section-intro--coral" /></div></section>
    <section className="soft-panel py-16 lg:py-24"><div className="container"><SectionIntro eyebrow="Why partner with TYA" title="A purposeful place to build." description="Bring practical, experience-led learning to your city through a community-centred model with a clear programme rhythm." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="content-card"><Building2 className="text-[#0e9c8c]" /><h3>Purpose-led model</h3><p>Bring practical, experience-led learning to young adults in your city.</p></article><article className="content-card"><Zap className="text-[#f28d63]" /><h3>Distinctive experience</h3><p>Missions, Pods and Growth Cards create a clear, differentiated parent proposition.</p></article><article className="content-card"><Users className="text-[#7a6316]" /><h3>Community-minded</h3><p>Build a local centre where young adults, families and coaches feel they belong.</p></article><article className="content-card"><TrendingUp className="text-[#0e9c8c]" /><h3>Room to grow</h3><p>A clear programme rhythm, repeatable delivery and lasting family relationships create a strong foundation for sustained local growth.</p></article></div></div></section>
    <section className="container py-16 lg:py-24"><SectionIntro eyebrow="What the conversation will cover" title={<>A partnership built for <span className="font-display italic headline-accent headline-accent--butter"><strong className="headline-impact">care.</strong></span></>} description="A first conversation can explore the practical, local and commercial foundations of a TYA partnership." /><ul className="grid gap-3 text-base leading-7 text-muted-copy sm:grid-cols-2">{["Your city, centre and local community", "Coach recruitment and programme delivery", "Parent experience, admissions and trial sessions", "Brand, curriculum and operational support", "The commercial model and next steps"].map((item) => <li key={item} className="flex gap-3"><Check className="mt-1 shrink-0 text-[#0e9c8c]" size={20} />{item}</li>)}</ul></section>
    <section className="soft-panel py-20"><div className="container"><SectionIntro eyebrow="Interested?" title="Let’s explore the fit." description="Start with a conversation about your city and the young adults you want to support." action={<Link className="btn-dark inline-flex items-center rounded-full px-6 py-4 text-sm font-bold" href="/contact">Contact the team</Link>} /></div></section>
  </PageShell>;
}
