import { ArrowRight, HeartHandshake, Sparkles, Users } from "lucide-react";
import { PageHero, PageShell, SectionLabel } from "../components/SiteChrome";

export default function OurStory() {
  return <PageShell>
    <PageHero eyebrow="Our story" title={<>They meet. They question. They <span className="font-display italic headline-accent headline-accent--butter"><strong className="headline-impact">become.</strong></span></>} intro="TYA Club was born from a simple question: What if young adults had a space to learn the things that classrooms often don't teach?" />
    <section className="container grid gap-14 py-16 lg:grid-cols-[.8fr_1.2fr] lg:py-24"><div><SectionLabel>The idea</SectionLabel><h2 className="mt-5 text-balance text-5xl font-medium leading-[.96] tracking-[-.05em] sm:text-6xl">A room for the person they are <span className="font-display italic headline-accent headline-accent--coral"><strong className="headline-impact">becoming.</strong></span></h2></div><div className="space-y-6 text-lg leading-8 text-muted-copy"><p>The idea was founded by Kiran Babu P, following nearly a decade of research, observation and conversations across multiple cities, exploring what young adults need to become confident, independent and future-ready.</p><p>Anoop Jaju and Sreyansh Jain joined the journey, bringing fresh perspectives, energy and ideas to the concept. Together, they reimagined the idea and gave it a new identity — TYA Club: Transforming Young Adults.</p><p>Today, TYA is envisioned as a space where young adults don't simply learn from someone at the front of a room. They meet, interact, question, experiment, share, play, reflect and learn from one another.</p><p>Because preparing young adults for the future isn't just about what they know. It's about who they become.</p></div></section>
    <section className="soft-panel py-16 lg:py-24"><div className="container"><SectionLabel>Our point of view</SectionLabel><h2 className="mt-5 max-w-[760px] text-balance text-5xl font-medium leading-[.96] tracking-[-.05em] sm:text-6xl">Confidence is not a personality trait. It is a <span className="font-display italic headline-accent headline-accent--butter"><strong className="headline-impact">practice.</strong></span></h2><div className="mt-14 grid gap-4 md:grid-cols-3"><article className="content-card"><Users size={20} className="text-[#0e9c8c]" /><h3>Belong before you lead</h3><p>Pods create the safety and familiarity young adults need to participate in their own way.</p></article><article className="content-card"><Sparkles size={20} className="text-[#f28d63]" /><h3>Make skills feel useful</h3><p>Missions give communication, judgment and ownership a real reason to matter.</p></article><article className="content-card"><HeartHandshake size={20} className="text-[#7a6316]" /><h3>Keep parents in the loop</h3><p>Growth is made visible through coach observations, reflection and the monthly Growth Card.</p></article></div></div></section>
    <section className="container flex flex-col items-start justify-between gap-8 py-16 sm:flex-row sm:items-center"><div><SectionLabel>Start here</SectionLabel><h2 className="mt-4 text-4xl font-medium">Give them one hour to try.</h2></div><a className="btn-dark rounded-full px-6 py-4 text-sm font-bold" href={`${import.meta.env.BASE_URL}#parents`}>See the parent view <ArrowRight className="ml-2 inline" size={16} /></a></section>
  </PageShell>;
}
