import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { PageHero, PageShell, SectionLabel } from "../components/SiteChrome";

const guides = [
  ["He has great ideas. Getting started is what matters.", "Having an idea is exciting. Turning it into action can feel much harder when they don't know where to begin or are afraid of getting it wrong.", "TYA gives them Missions, projects and challenges where they have to turn an idea into action — plan it, try it, adjust it and move forward."],
  ["She really doesn't know what to do when things don't go her way — she panics.", "When young people are used to knowing what comes next, an unexpected change can feel overwhelming. They need practice staying with a problem when the original plan no longer works.", "That’s why TYA has The Twist — challenges deliberately change, forcing them to pause, rethink and decide what to do next."],
  ["He knows exactly what he wants to say — when it's time, he gasps.", "Knowing what you think is one thing. Saying it when everyone is listening is another.", "TYA creates real reasons to speak — presenting, negotiating, debating and defending ideas — so confidence grows through practice, not instruction."],
  ["She cares so much about the world. Sometimes I wonder where she thinks she fits into it.", "Young people can care deeply about big issues while feeling that someone else should solve them. What they often need is an opportunity to experience their own ability to make a difference.", "Through Earth, community and civic Missions, TYA turns “someone should do something” into “what can we do?”"],
  ["He loves being part of the team — but whenever a chance comes, he rejects it.", "Being part of a team feels comfortable. Taking responsibility can feel much riskier.", "TYA gives every young person opportunities to lead, decide, coordinate and take responsibility — without making leadership about being the loudest person in the room."],
  ["Give her ten options and somehow… none of them work for her.", "Too many choices can sometimes create more uncertainty, especially when they're worried about making the wrong one. Decision-making gets stronger when young people actually get to practise it.", "TYA puts them into situations where choices have consequences, so they learn to make thoughtful decisions rather than wait for the perfect one."],
  ["He's so excited when he starts something. And loses interest at the same speed.", "Starting is exciting. Staying with something after the novelty disappears is a skill of its own.", "TYA gives them challenges that require persistence, teamwork and follow-through — especially when the exciting part is over."],
  ["She knows exactly what everyone else wants to become. She's still figuring herself out.", "Young people see what everyone around them is doing while still discovering their own strengths, interests and values. They don't always need a career answer yet — they need experiences that help them discover themselves.", "TYA lets them lead, create, negotiate, solve and experiment in different roles — giving them more chances to discover what feels like them."],
  ["She has a voice. I just wish she'd use it more.", "Some young people have plenty to say but hesitate when the room feels unfamiliar or they aren't sure their opinion will matter.", "At TYA, their voice has a purpose — the Pod needs their idea, the Mission needs their decision and the Arena needs their point of view."],
  ["He'll spot the problem. Then wait for someone else to do something about it.", "Noticing a problem is easy. Taking responsibility for doing something about it is a skill that develops through experience.", "TYA gives young people problems without immediately giving them the answer — asking them to notice, decide, act and own the outcome."],
  ["Her attention can be everywhere at once. Getting it to stay in one place is the tricky part.", "With constant stimulation around them, directing attention can be difficult — especially when something feels repetitive or disconnected from purpose.", "TYA makes focus part of the experience: a Mission has a goal, a Pod needs them and the clock is moving. They have a reason to pay attention."],
  ["When life doesn't go to plan, she feels like everything has fallen apart.", "For a young person, one rejection, failure, breakup or disappointment can sometimes feel like the whole world has collapsed. They need to know that a painful moment is not the end of their story — and that reaching out is part of finding a way through.", "TYA gives them repeated practice with setbacks, uncertainty and unexpected change — learning to pause, seek support, regain perspective and find a way forward."],
] as const;

export default function ParentGuides() {
  const [open, setOpen] = useState<number | null>(0);
  return <PageShell>
    <PageHero eyebrow="For parents" title={<>The questions parents actually ask, answered <span className="font-display italic text-[#f6d77a]">properly.</span></>} intro="Written by coaches, not by a marketing team. Practical context for families deciding whether TYA is right for their young person." />
    <section className="container grid gap-12 py-24 lg:grid-cols-[.65fr_1.35fr] lg:py-32"><div className="lg:sticky lg:top-28 lg:self-start"><SectionLabel>Parent Guides</SectionLabel><h2 className="mt-5 text-5xl font-medium leading-[.96] tracking-[-.05em] sm:text-6xl">Good questions deserve <span className="font-display italic text-[#7a6316]">room.</span></h2><p className="mt-7 text-lg leading-8 text-muted-copy">Click a question to see what may be happening and how TYA responds through experience, not instruction.</p></div><div className="faq-list">{guides.map(([question, why, response], index) => <div className="faq-item" key={question}><button className="faq-trigger" onClick={() => setOpen(open === index ? null : index)} aria-expanded={open === index}><span><span className="mr-3 text-xs font-bold text-[#f28d63]">{String(index + 1).padStart(2, "0")}</span>{question}</span><ChevronDown className={open === index ? "rotate-180" : ""} size={18} /></button>{open === index && <div className="faq-answer"><p><strong>Why this happens</strong>{why}</p><p><strong>TYA response</strong>{response}</p></div>}</div>)}</div></section>
  </PageShell>;
}
